# Generated by Django 4.0.4 on 2022-06-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_shopname_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shopname',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
