# Generated by Django 4.0.4 on 2022-06-09 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_shopname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shopname',
        ),
    ]
